### ISSUE TITLE
where not working as expected

### ISSUE THREAD

**Issue by ImLunaHey** [demonsters/prisma-mock#22] opened 2023-02-27 01:12 UTC
In my application I don't get this behavior so I'm guessing there's a bug with the `where` field.

```ts
import type { prisma } from '@app/server/db';
import { randomUUID } from 'crypto';
import createPrismaMock from 'prisma-mock';

describe('prisma-mock', () => {
    it('can be used to mock prisma', async () => {
        const prismaMock = createPrismaMock<NonNullable<typeof prisma>>();
        const userId1 = randomUUID();
        const userId2 = randomUUID();
        const userId3 = randomUUID();

        // Create a page and user
        await prismaMock.user.create({
            data: {
                id: userId1,
                page: {
                    create: {
                        id: randomUUID(),
                        handle: 'testuser1',
                        displayName: 'Test User 1',
                        ownerId: userId1,
                    },
                },
            },
        });

        // Create a second page and user
        await prismaMock.user.create({
            data: {
                id: userId2,
                page: {
                    create: {
                        id: randomUUID(),
                        handle: 'testuser2',
                        displayName: 'Test User 2',
                        ownerId: userId2,
                    },
                },
            },
        });

        // Create a third page and user
        await prismaMock.user.create({
            data: {
                id: userId3,
                page: {
                    create: {
                        id: randomUUID(),
                        handle: 'testuser3',
                        displayName: 'Test User 3',
                        ownerId: userId3,
                    },
                },
            },
        });

        // user3 blocks user2
        // If we comment this out it works as expected
        await prismaMock.block.create({
            data: {
                blocker: {
                    connect: {
                        userId: userId3,
                    },
                },
                blocked: {
                    connect: {
                        userId: userId2,
                    },
                },
                createdAt: new Date(2023, 1, 27, 1, 6, 45, 709),
            },
        });

        // Check if user1 is blocked by user2
        const blockedBy = await prismaMock.block.findMany({
            where: {
                blocked: {
                    id: userId1,
                },
                blocker: {
                    id: userId2,
                },
            },
            include: {
                blocked: true,
                blocker: true,
            },
        });

        // This should return an empty array since user1 is not blocked by user2
        // Instead it returns an array like this
        // [
        //     {
        //       "blocked": {
        //         "deactivatedTimestamp": null,
        //         "description": "",
        //         "displayName": "Test User 2",
        //         "followerCount": 0,
        //         "handle": "testuser2",
        //         "id": "550ac7d6-63c6-4b06-a693-d4258bd096de",
        //         "image": null,
        //         "official": false,
        //         "ownerId": "496f1985-ef8b-492a-aa8b-dc7dea07b44f",
        //         "userId": "496f1985-ef8b-492a-aa8b-dc7dea07b44f",
        //       },
        //       "blockedId": "550ac7d6-63c6-4b06-a693-d4258bd096de",
        //       "blocker": {
        //         "deactivatedTimestamp": null,
        //         "description": "",
        //         "displayName": "Test User 3",
        //         "followerCount": 0,
        //         "handle": "testuser3",
        //         "id": "8035bb4c-1112-49ae-b826-ee258cfa7a20",
        //         "image": null,
        //         "official": false,
        //         "ownerId": "34a691f3-2ed9-4b3f-b574-7dd32ca8c90f",
        //         "userId": "34a691f3-2ed9-4b3f-b574-7dd32ca8c90f",
        //       },
        //       "blockerId": "8035bb4c-1112-49ae-b826-ee258cfa7a20",
        //       "createdAt": 2023-02-26T14:36:45.709Z,
        //     },
        //   ]
        expect(blockedBy).toHaveLength(0);
    });
});
```

**Comment by ImLunaHey** [comment] 2023-02-28 06:04
The following should return pages where the user's ID matches, instead we just get a random result?

```ts
const currentPage = await ctx.prisma?.page.findFirst({
    where: {
        user: {
            id: ctx.session.user?.id
        },
    }
});

console.log({
    where: {
        user: {
            id: ctx.session.user?.id
        },
    }
}, currentPage);

// { where: { user: { id: '024c4956-0552-468e-8ad0-1a99f2d00d2d' } } } {
//     id: '146d8965-e61d-4483-80b5-0b82ebd4dd09',
//     handle: 'testuser1',
//     displayName: 'Test User 1',
//     ownerId: '2923508e-76cd-4648-9907-f8ab3303c197',
//     image: null,
//     followerCount: 0,
//     official: false,
//     description: '',
//     deactivatedTimestamp: null,
//     userId: '2923508e-76cd-4648-9907-f8ab3303c197'
//   }
```

**Comment by stijnvanderlaan** [comment] 2023-02-28 09:11
Hey @ImLunaHey thanks for your feedback, I can reproduce this.

**Comment by stijnvanderlaan** [comment] 2023-02-28 09:45
This is probably fixed in v0.4.1, can you confirm?

**Comment by ImLunaHey** [comment] 2023-02-28 10:25
This has somewhat fixed the issue but there's still something weird going on with `where`.

```ts
it('returns a list of message threads if the user has message threads', async () => {
  const prismaMock = createPrismaMock<NonNullable<typeof prisma>>();
  const session = createMockSession();
  const page = await prismaMock.page.create({
      data: {
          id: randomUUID(),
          displayName: 'Test Page',
          handle: 'testpage',
          owner: {
              connect: {
                  id: session.user.id,
              },
          },
      }
  });
  await prismaMock.messageThread.create({
      data: {
          id: randomUUID(),
          participants: {
              connect: [{
                  id: page.id
              }],
          },
      },
  });

  const allMessageThreads = await prismaMock.messageThread.findMany({
      include: {
          messages: true,
          participants: true
      }
  });
  expect(allMessageThreads.length).toBe(1);
  expect(allMessageThreads[0]).toHaveProperty('id');
  expect(allMessageThreads[0]).toHaveProperty('participants');
  expect(allMessageThreads[0]?.participants.length).toBe(1);
  expect(allMessageThreads[0]?.participants[0]?.handle).toBe('testpage');
  expect(allMessageThreads[0]?.participants[0]?.ownerId).toBe(session.user.id);

  const messageThreads = await prismaMock.messageThread.findMany({
      where: {
          participants: {
              some: {
                  owner: {
                      id: session.user?.id
                  }
              }
          }
      },
      include: {
          messages: true,
          participants: true
      }
  });

  // This is 0 when it should be 1
  expect(messageThreads.length).toBe(1);
  expect(messageThreads[0]).toHaveProperty('id');
  expect(messageThreads[0]).toHaveProperty('participants');
  expect(messageThreads[0]?.participants.length).toBe(1);
  expect(messageThreads[0]?.participants[0]?.handle).toBe('testpage');
  expect(messageThreads[0]?.participants[0]?.ownerId).toBe(session.user.id);
});
```

**Comment by stijnvanderlaan** [comment] 2023-02-28 15:30
The new version (v0.5.0) will probably fix this to.

**Comment by ImLunaHey** [comment] 2023-03-01 00:35
Looks like that's solved some of it but now I'm getting a different issue. I'm pretty sure this was passing before the last 2 updates.

```ts
FAIL  __tests__/services/page-service.test.ts
● pageService › getUsersPages › returns pages the user is an moderator of

  TypeError: Cannot read properties of null (reading 'id')

    130 |         if (!ctx.session.user) throw new Error('Not signed in.');
    131 |
  > 132 |         return ctx.prisma?.page.findMany({
        |                                 ^
    133 |             where: {
    134 |                 OR: [{
    135 |                     ownerId: ctx.session.user.id,

    at node_modules/prisma-mock/lib/index.js:110:109
        at Array.filter (<anonymous>)
    at getFieldRelationshipWhere (node_modules/prisma-mock/lib/index.js:110:67)
    at matchItem (node_modules/prisma-mock/lib/index.js:521:37)
    at matchItems (node_modules/prisma-mock/lib/index.js:621:22)
    at node_modules/prisma-mock/lib/index.js:631:42
        at Array.some (<anonymous>)
    at matchOr (node_modules/prisma-mock/lib/index.js:631:26)
    at matchItem (node_modules/prisma-mock/lib/index.js:473:24)
    at matchItems (node_modules/prisma-mock/lib/index.js:621:22)
    at node_modules/prisma-mock/lib/index.js:635:24
        at Array.filter (<anonymous>)
    at Object.findMany (node_modules/prisma-mock/lib/index.js:659:18)
    at Proxy.<anonymous> (node_modules/prisma-mock/lib/index.js:936:37)
    at PageService.findMany [as getUsersPages] (src/services/page-service.ts:132:33)
    at Object.getUsersPages (__tests__/services/page-service.test.ts:221:49)
```

https://github.com/ImLunaHey/lunacity/blob/11c99acca1a1e26f94c8cbc64efa95f295fbb2c7/__tests__/services/page-service.test.ts#L201-L228

```ts
it('returns pages the user is an moderator of', async () => {
    const session = createMockSession();
    const prismaMock = createPrismaMock<NonNullable<typeof prisma>>();
    await prismaMock.page.create({
        data: {
            handle: 'staff',
            displayName: '@staff',
            owner: {
                create: {
                    id: randomUUID()
                }
            },
            moderators: {
                create: createMockUser({
                    id: session.user.id
                })
            }
        }
    });

    const userPages = await pageService.getUsersPages({
        prisma: prismaMock,
        session,
    });
    expect(userPages.length).toBe(1);
    expect(userPages[0]?.handle).toBe('staff');
});
```

**Comment by stijnvanderlaan** [comment] 2023-05-30 14:47
I close this issue because, please reply if there are still any issues.

**Closed by stijnvanderlaan** 2023-05-30 14:47 UTC
